### PR TITLE
Fix caching issues

### PR DESCRIPTION
**Pull request by samansmink**
Fixes https://github.com/duckdb/duckdb/issues/8944

### CODE REVIEW

**Comment by domoritz** [comment]
Is there anything left here. It would be nice to get this in so we can update duckdb in mosaic (https://github.com/uwdata/mosaic/pull/215).

**Comment by mingfang** [comment]
please merge

**Comment by jheer** [comment]
Would love to see progress here. The node.js client with arrow extension is currently unusable with some queries. If fixed we can update the Mosaic project to the latest DuckDB and provide server-side access to the latest features. Thank you!!

**Comment by samansmink** [comment]
Apologies for neglecting things here, the arrow extension is quite low on our very full priorities list atm. If you feel like this is unjustified, please ping me or @hannes

I will make an effort to get the arrow extension ready for the upcoming v0.10 by fixing ci here and merging this

**Comment by jheer** [comment]
Thank you @samansmink! I'm sure prioritization must be tricky given the large surface area of extensions and clients in addition to the DuckDB core. I also understand that data analysts/engineers working in Python or R may be a bigger audience right now. That said, I'd still put in a strong plug for a high-quality JS client which, alongside DuckDB-WASM, provides a solid base for developing DuckDB-powered web applications in JavaScript.

In this specific case, the bugs effectively make working with the node client and using Arrow for efficient transfer impossible for certain (in our case, common) queries. So I hope the severity of the issue also helps influence priorities for both fixes and test coverage.

In any case, thanks again. The DuckDB ecosystem is enabling exciting new possibilities and I appreciate the team's efforts.

**Comment by domoritz** [comment]
Thank you for making time for this fix @samansmink!

**Pull request merged**
